### PR TITLE
Update ua-parser to uap-core

### LINKED ISSUE #20: Git submodule should point to uap-core
The git submodule in this repo still points at https://github.com/tobie/ua-parser, but per the README:

> # ua-parser has moved
> 
> This project has moved to a new project space [ua-parser](https://github.com/ua-parser), separating the regexes from the parsers for the different languages into their own repos:
> 
> * [uap-core](https://github.com/ua-parser/uap-core) : The regex file necessary to build language ports of Browserscope's user agent parser.

I figure this will probably be fixed the next time the gem is bumped to get an updated database (BTW, uap-core *has* updated since the last version of this gem), but I thought I'd make this issue explicit just in case. ;)

### PR DESCRIPTION
**Pull request by efouts**
Closes #20. Thanks to @wallin, I picked up where you left off.

- Replace ua-parser with uap-core
- Handle regex_flag for case-sensitive regexes
- Strip device family
- Fixed defect where all sub calls were being passed $1

### CODE REVIEW

**Comment by efouts** [comment]
\cc @wallin

**Comment by efouts** [comment]
\cc @toolmantim

**Comment by toolmantim** [comment]
Hey nice, this looks great! 

@tobie can we please get @efouts added to the Ruby team?

@efouts I couldn't find your RubyGems email to add you as an owner, so you can cut releases.

**Comment by toolmantim** [comment]
Also I just pushed out a 2.3.0 release with these updates! :+1: :tada:

**Comment by efouts** [comment]
@toolmantim Thanks, I need to signup, [This](https://rubygems.org/profiles/efouts) is me, efouts@qualtrax.com

**Comment by toolmantim** [comment]
@efouts added!

**Comment by wallin** [comment]
Great work @efouts! Thanks for picking this up again

**Comment by mdb** [comment]
:+1: Thank you!

**Pull request merged**
