### PR TITLE
updates-2023-01-31

### PR DESCRIPTION
**Pull request by opti**

### CODE REVIEW

**Comment by nijikon** [comment]
@opti is there an easy fix for jruby?

**Comment by nijikon** [comment]
Refs https://github.com/jruby/jruby/issues/7543

**Comment by nijikon** [comment]
I suggest dropping checks on JRuby or blocking it to `9.3.8.0` which should fix it.

**Review by nijikon — APPROVED** [review]

**Comment by opti** [comment]
@nijikon thank you 🙌

**Pull request merged**
