### PR TITLE
Parse device brand and model

### PR DESCRIPTION
**Pull request by seandilda**
This commit adds parsing for the device brand and model.

It also updates to latest uap-core as previously referenced commit is no longer available

### CODE REVIEW

**Comment by wallin** [comment]
Thanks @seandilda. This looks good to me. Would you mind rebasing from master to resolve the conflict?

**Comment by wallin** [comment]
Hey @seandilda Do you expect to be able to do the rebase soon? I'd be happy to bring in these changes once done

**Comment by wallin** [comment]
Thanks! @toolmantim any objections?

**Comment by toolmantim** [comment]
None here @wallin! I no longer use the gem, so I'm happy for you to make executive calls 😊

**Pull request merged**
